{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2020-03-03T10:30:08.009Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","timestamp":"2020-03-03T10:30:08.010Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2020-03-03T10:30:08.221Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","timestamp":"2020-03-03T10:30:08.222Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2020-03-03T10:30:08.686Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","timestamp":"2020-03-03T10:30:08.687Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2020-03-03T10:30:09.113Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","timestamp":"2020-03-03T10:30:09.113Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2020-03-03T10:30:09.215Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","timestamp":"2020-03-03T10:30:09.216Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2020-03-03T10:32:08.029Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","timestamp":"2020-03-03T10:32:08.029Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2020-03-03T10:32:08.098Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","timestamp":"2020-03-03T10:32:08.099Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2020-03-03T10:32:08.331Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","timestamp":"2020-03-03T10:32:08.331Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2020-03-03T10:32:08.753Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","timestamp":"2020-03-03T10:32:08.753Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2020-03-03T10:32:08.809Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","timestamp":"2020-03-03T10:32:08.809Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2020-03-03T10:34:08.520Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","timestamp":"2020-03-03T10:34:08.521Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2020-03-03T10:34:08.619Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","timestamp":"2020-03-03T10:34:08.620Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2020-03-03T10:34:08.985Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","timestamp":"2020-03-03T10:34:08.985Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2020-03-03T10:34:09.495Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","timestamp":"2020-03-03T10:34:09.496Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2020-03-03T10:34:11.023Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","timestamp":"2020-03-03T10:34:11.023Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2020-03-03T10:36:09.052Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","timestamp":"2020-03-03T10:36:09.053Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2020-03-03T10:36:09.302Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","timestamp":"2020-03-03T10:36:09.303Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2020-03-03T10:36:09.746Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","timestamp":"2020-03-03T10:36:09.746Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2020-03-03T10:36:10.200Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","timestamp":"2020-03-03T10:36:10.200Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2020-03-03T10:36:11.744Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","timestamp":"2020-03-03T10:36:11.745Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2020-03-03T10:38:09.415Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","timestamp":"2020-03-03T10:38:09.415Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2020-03-03T10:38:09.637Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","timestamp":"2020-03-03T10:38:09.638Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2020-03-03T10:38:10.124Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","timestamp":"2020-03-03T10:38:10.125Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2020-03-03T10:38:10.516Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","timestamp":"2020-03-03T10:38:10.516Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2020-03-03T10:38:11.198Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","timestamp":"2020-03-03T10:38:11.199Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T12:46:06.668Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T12:46:06.686Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T12:46:06.686Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T12:46:06.687Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T12:46:06.704Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T12:46:06.718Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T12:46:06.719Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T12:46:06.743Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T12:46:06.744Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T12:46:06.748Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T12:46:27.934Z"}
{"error":{"code":101,"message":"Invalid username/password."},"level":"error","message":"Error generating response. ParseError { code: 101, message: 'Invalid username/password.' }","timestamp":"2020-03-03T13:05:17.353Z"}
{"code":101,"message":"Invalid username/password.","level":"error","timestamp":"2020-03-03T13:05:17.354Z"}
{"error":{"code":111,"message":"schema mismatch for Hola.Hi; expected Boolean but got String"},"level":"error","message":"Error generating response. ParseError {\n  code: 111,\n  message: 'schema mismatch for Hola.Hi; expected Boolean but got String' }","timestamp":"2020-03-03T13:43:45.926Z"}
{"code":111,"message":"schema mismatch for Hola.Hi; expected Boolean but got String","level":"error","timestamp":"2020-03-03T13:43:45.928Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:49:12.801Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:49:12.802Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:49:12.811Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:49:12.816Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:49:12.820Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:49:12.821Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:49:17.325Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:49:23.117Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:49:23.118Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:49:23.119Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:52:48.462Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:52:48.463Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:52:53.223Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:52:53.223Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:52:53.224Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:53:26.700Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:53:26.709Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:53:26.710Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:53:26.713Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:53:26.835Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:53:26.869Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:53:26.888Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:53:26.923Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:53:26.924Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:53:26.925Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:53:30.481Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:53:30.492Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:53:56.614Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:53:56.618Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:53:56.619Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:53:56.620Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:53:56.682Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:53:56.686Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:53:56.689Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:53:56.711Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:53:56.713Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:53:56.713Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:54:01.947Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:54:01.955Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:54:02.721Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:54:02.738Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:55:54.082Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:55:54.083Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:55:54.084Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:55:55.100Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:55:55.101Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:55:55.104Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:55:55.105Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:55:55.195Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:55:55.210Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:55:55.224Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:55:55.237Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:55:55.247Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:55:55.248Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:56:19.407Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:56:49.945Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:56:49.968Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:56:49.969Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:56:49.970Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:56:50.034Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:56:50.045Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:56:50.052Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:56:50.073Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:56:50.074Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:56:50.075Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-03-03T13:56:59.871Z"}
{"className":"Task","triggerType":"beforeSave","error":{"code":141},"user":"DEaw9FXHnS","level":"error","message":"beforeSave failed for Task for user DEaw9FXHnS:\n  Input: {\"duedate\":{\"__type\":\"Date\",\"iso\":\"2020-03-03T13:57:34.200Z\"},\"creator\":{\"__type\":\"Pointer\",\"className\":\"_User\",\"objectId\":\"DEaw9FXHnS\"},\"project\":{\"__type\":\"Pointer\",\"className\":\"Project\",\"objectId\":\"hwDcniLNJ0\"},\"name\":\"dd\",\"content\":\"dd\",\"userdue\":{\"__type\":\"Pointer\",\"className\":\"_User\",\"objectId\":\"DEaw9FXHnS\"},\"completed\":false}\n  Error: {\"code\":141}","timestamp":"2020-03-03T13:57:45.960Z"}
{"error":{"code":141},"level":"error","message":"Error generating response. ParseError { code: 141, message: undefined }","timestamp":"2020-03-03T13:57:45.961Z"}
{"code":141,"message":"undefined","level":"error","timestamp":"2020-03-03T13:57:45.962Z"}
{"className":"Task","triggerType":"beforeSave","error":{"code":141},"user":"DEaw9FXHnS","level":"error","message":"beforeSave failed for Task for user DEaw9FXHnS:\n  Input: {\"duedate\":{\"__type\":\"Date\",\"iso\":\"2020-03-03T13:57:34.200Z\"},\"creator\":{\"__type\":\"Pointer\",\"className\":\"_User\",\"objectId\":\"DEaw9FXHnS\"},\"project\":{\"__type\":\"Pointer\",\"className\":\"Project\",\"objectId\":\"hwDcniLNJ0\"},\"name\":\"dd\",\"content\":\"dd\",\"userdue\":{\"__type\":\"Pointer\",\"className\":\"_User\",\"objectId\":\"DEaw9FXHnS\"},\"completed\":false}\n  Error: {\"code\":141}","timestamp":"2020-03-03T13:57:53.719Z"}
{"error":{"code":141},"level":"error","message":"Error generating response. ParseError { code: 141, message: undefined }","timestamp":"2020-03-03T13:57:53.720Z"}
{"code":141,"message":"undefined","level":"error","timestamp":"2020-03-03T13:57:53.720Z"}
